# docker-compose.yml
version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./v1:/var/www/html
    networks:
      - symfony_net

  nginx:
    image: nginx:latest
    volumes:
      - ./v1:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
    depends_on:
      - php-fpm
    networks:
      - symfony_net

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - symfony_net

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: rabbitmq_password
    networks:
      - symfony_net

volumes:
  mysql_data:

networks:
  symfony_net:
    driver: bridge